name = "agar-server-example"
address = "127.0.0.1:8086"

[[modules]]
abi_version = 6
name = "agar-server"
visibility = "Public"
queries = []
subscriptions = []
authorities = []
module_dependencies = []
node_dependencies = []
replicated_tables = []

[modules.version]
major = 0
minor = 1
patch = 0

[[modules.reducers]]
name = "tick"
arguments = []

[[modules.reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "food"

[[modules.reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "deadplayer"

[[modules.reducers.inserts]]
node_selection = "Current"
module_selection = "Current"
table_name = "food"

[[modules.reducers.inserts]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.reducers.inserts]]
node_selection = "Current"
module_selection = "Current"
table_name = "deadplayer"

[[modules.reducers.updates]]
node_selection = "Current"
module_selection = "Current"
table_name = "food"

[[modules.reducers.updates]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.reducers.deletes]]
node_selection = "Current"
module_selection = "Current"
table_name = "food"

[[modules.reducers.deletes]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.reducers.deletes]]
node_selection = "Current"
module_selection = "Current"
table_name = "deadplayer"

[[modules.reducers]]
name = "join"
updates = []
deletes = []

[[modules.reducers.arguments]]
name = "name"
field_type = "String"

[[modules.reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.reducers.inserts]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.reducers]]
name = "set_direction"
inserts = []
deletes = []

[[modules.reducers.arguments]]
name = "dx"
field_type = "F32"

[[modules.reducers.arguments]]
name = "dy"
field_type = "F32"

[[modules.reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.reducers.updates]]
node_selection = "Current"
module_selection = "Current"
table_name = "player"

[[modules.tables]]
name = "player"
type_name = "Player"
visibility = "Public"
primary_key_auto_inc = false
indexes = []
persistence = "Stateful"

[[modules.tables.fields]]
name = "name"
field_type = "String"

[[modules.tables.fields]]
name = "pos"

[modules.tables.fields.field_type]
Named = "Vec2"

[[modules.tables.fields]]
name = "dir"

[modules.tables.fields.field_type]
Named = "Vec2"

[[modules.tables.fields]]
name = "radius"
field_type = "F32"

[[modules.tables.fields]]
name = "color"

[modules.tables.fields.field_type]
Named = "Color"

[modules.tables.primary_key]
name = "id"
field_type = "String"

[[modules.tables]]
name = "deadplayer"
type_name = "DeadPlayer"
visibility = "Public"
fields = []
primary_key_auto_inc = false
indexes = []
persistence = "Stateful"

[modules.tables.primary_key]
name = "id"
field_type = "String"

[[modules.tables]]
name = "food"
type_name = "Food"
visibility = "Public"
primary_key_auto_inc = true
indexes = []
persistence = "Stateful"

[[modules.tables.fields]]
name = "pos"

[modules.tables.fields.field_type]
Named = "Vec2"

[[modules.tables.fields]]
name = "radius"
field_type = "F32"

[[modules.tables.fields]]
name = "color"

[modules.tables.fields.field_type]
Named = "Color"

[modules.tables.primary_key]
name = "id"
field_type = "U64"

[modules.type_definitions.Vec2.Struct]
name = "Vec2"

[[modules.type_definitions.Vec2.Struct.fields]]
name = "x"
field_type = "F32"

[[modules.type_definitions.Vec2.Struct.fields]]
name = "y"
field_type = "F32"

[modules.type_definitions.Color.Struct]
name = "Color"

[[modules.type_definitions.Color.Struct.fields]]
name = "r"
field_type = "F32"

[[modules.type_definitions.Color.Struct.fields]]
name = "g"
field_type = "F32"

[[modules.type_definitions.Color.Struct.fields]]
name = "b"
field_type = "F32"

[modules.type_definitions.Player.Struct]
name = "Player"

[[modules.type_definitions.Player.Struct.fields]]
name = "id"
field_type = "String"

[[modules.type_definitions.Player.Struct.fields]]
name = "name"
field_type = "String"

[[modules.type_definitions.Player.Struct.fields]]
name = "pos"

[modules.type_definitions.Player.Struct.fields.field_type]
Named = "Vec2"

[[modules.type_definitions.Player.Struct.fields]]
name = "dir"

[modules.type_definitions.Player.Struct.fields.field_type]
Named = "Vec2"

[[modules.type_definitions.Player.Struct.fields]]
name = "radius"
field_type = "F32"

[[modules.type_definitions.Player.Struct.fields]]
name = "color"

[modules.type_definitions.Player.Struct.fields.field_type]
Named = "Color"

[modules.type_definitions.DeadPlayer.Struct]
name = "DeadPlayer"

[[modules.type_definitions.DeadPlayer.Struct.fields]]
name = "id"
field_type = "String"

[modules.type_definitions.Food.Struct]
name = "Food"

[[modules.type_definitions.Food.Struct.fields]]
name = "id"
field_type = "U64"

[[modules.type_definitions.Food.Struct.fields]]
name = "pos"

[modules.type_definitions.Food.Struct.fields.field_type]
Named = "Vec2"

[[modules.type_definitions.Food.Struct.fields]]
name = "radius"
field_type = "F32"

[[modules.type_definitions.Food.Struct.fields]]
name = "color"

[modules.type_definitions.Food.Struct.fields.field_type]
Named = "Color"
