abi_version = 6
name = "ui"
visibility = "Public"
queries = []
subscriptions = []
authorities = []
node_dependencies = []
replicated_tables = []

[version]
major = 0
minor = 1
patch = 0

[[reducers]]
name = "set_focus"
inserts = []
deletes = []

[[reducers.arguments]]
name = "id"
field_type = "String"

[[reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "inputfocus"

[[reducers.updates]]
node_selection = "Current"
module_selection = "Current"
table_name = "inputfocus"

[[reducers]]
name = "clear_focus"
arguments = []
inserts = []
deletes = []

[[reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "inputfocus"

[[reducers.updates]]
node_selection = "Current"
module_selection = "Current"
table_name = "inputfocus"

[[reducers]]
name = "clear_elements"
arguments = []
inserts = []
updates = []

[[reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "uielement"

[[reducers.deletes]]
node_selection = "Current"
module_selection = "Current"
table_name = "uielement"

[[reducers]]
name = "create_element"
reads = []
updates = []
deletes = []

[[reducers.arguments]]
name = "element"

[reducers.arguments.field_type]
Named = "UiElement"

[[reducers.inserts]]
node_selection = "Current"
module_selection = "Current"
table_name = "uielement"

[[reducers]]
name = "delete_element"
inserts = []
updates = []

[[reducers.arguments]]
name = "id"
field_type = "String"

[[reducers.reads]]
node_selection = "Current"
module_selection = "Current"
table_name = "uielement"

[[reducers.deletes]]
node_selection = "Current"
module_selection = "Current"
table_name = "uielement"

[[reducers]]
name = "update_element"
reads = []
inserts = []
deletes = []

[[reducers.arguments]]
name = "element"

[reducers.arguments.field_type]
Named = "UiElement"

[[reducers.updates]]
node_selection = "Current"
module_selection = "Current"
table_name = "uielement"

[[tables]]
name = "uielement"
type_name = "UiElement"
visibility = "Public"
primary_key_auto_inc = false
indexes = []
persistence = "Logged"

[[tables.fields]]
name = "parent"

[tables.fields.field_type]
Option = "String"

[[tables.fields]]
name = "order"
field_type = "U32"

[[tables.fields]]
name = "width"

[tables.fields.field_type]
Named = "Size"

[[tables.fields]]
name = "height"

[tables.fields.field_type]
Named = "Size"

[[tables.fields]]
name = "layout_direction"

[tables.fields.field_type]
Named = "LayoutDirection"

[[tables.fields]]
name = "gap"
field_type = "F32"

[[tables.fields]]
name = "padding"
field_type = "F32"

[[tables.fields]]
name = "margin"
field_type = "F32"

[[tables.fields]]
name = "background_color"

[tables.fields.field_type]
Tuple = ["F32", "F32", "F32", "F32"]

[[tables.fields]]
name = "corner_radius"
field_type = "F32"

[[tables.fields]]
name = "border_width"
field_type = "F32"

[[tables.fields]]
name = "border_color"

[tables.fields.field_type]
Tuple = ["F32", "F32", "F32", "F32"]

[[tables.fields]]
name = "text"

[tables.fields.field_type]
Option = "String"

[[tables.fields]]
name = "text_size"
field_type = "F32"

[[tables.fields]]
name = "text_color"

[tables.fields.field_type]
Tuple = ["F32", "F32", "F32", "F32"]

[[tables.fields]]
name = "text_wrap"

[tables.fields.field_type]
Named = "TextWrap"

[[tables.fields]]
name = "is_input"
field_type = "Bool"

[[tables.fields]]
name = "cursor_pos"
field_type = "U32"

[[tables.fields]]
name = "scrollable_x"
field_type = "Bool"

[[tables.fields]]
name = "scrollable_y"
field_type = "Bool"

[[tables.fields]]
name = "scroll_x"
field_type = "F32"

[[tables.fields]]
name = "scroll_y"
field_type = "F32"

[[tables.fields]]
name = "visible"
field_type = "Bool"

[tables.primary_key]
name = "id"
field_type = "String"

[type_definitions.TextWrap.Enum]
name = "TextWrap"

[[type_definitions.TextWrap.Enum.variants]]
name = "None"
field_type = "Void"

[[type_definitions.TextWrap.Enum.variants]]
name = "Words"
field_type = "Void"

[[type_definitions.TextWrap.Enum.variants]]
name = "Newlines"
field_type = "Void"

[type_definitions.LayoutDirection.Enum]
name = "LayoutDirection"

[[type_definitions.LayoutDirection.Enum.variants]]
name = "Row"
field_type = "Void"

[[type_definitions.LayoutDirection.Enum.variants]]
name = "Column"
field_type = "Void"

[type_definitions.Size.Enum]
name = "Size"

[[type_definitions.Size.Enum.variants]]
name = "Fixed"
field_type = "F32"

[[type_definitions.Size.Enum.variants]]
name = "Grow"
field_type = "Void"

[[type_definitions.Size.Enum.variants]]
name = "Fit"
field_type = "Void"

[type_definitions.UiElement.Struct]
name = "UiElement"

[[type_definitions.UiElement.Struct.fields]]
name = "id"
field_type = "String"

[[type_definitions.UiElement.Struct.fields]]
name = "parent"

[type_definitions.UiElement.Struct.fields.field_type]
Option = "String"

[[type_definitions.UiElement.Struct.fields]]
name = "order"
field_type = "U32"

[[type_definitions.UiElement.Struct.fields]]
name = "width"

[type_definitions.UiElement.Struct.fields.field_type]
Named = "Size"

[[type_definitions.UiElement.Struct.fields]]
name = "height"

[type_definitions.UiElement.Struct.fields.field_type]
Named = "Size"

[[type_definitions.UiElement.Struct.fields]]
name = "layout_direction"

[type_definitions.UiElement.Struct.fields.field_type]
Named = "LayoutDirection"

[[type_definitions.UiElement.Struct.fields]]
name = "gap"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "padding"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "margin"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "background_color"

[type_definitions.UiElement.Struct.fields.field_type]
Tuple = ["F32", "F32", "F32", "F32"]

[[type_definitions.UiElement.Struct.fields]]
name = "corner_radius"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "border_width"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "border_color"

[type_definitions.UiElement.Struct.fields.field_type]
Tuple = ["F32", "F32", "F32", "F32"]

[[type_definitions.UiElement.Struct.fields]]
name = "text"

[type_definitions.UiElement.Struct.fields.field_type]
Option = "String"

[[type_definitions.UiElement.Struct.fields]]
name = "text_size"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "text_color"

[type_definitions.UiElement.Struct.fields.field_type]
Tuple = ["F32", "F32", "F32", "F32"]

[[type_definitions.UiElement.Struct.fields]]
name = "text_wrap"

[type_definitions.UiElement.Struct.fields.field_type]
Named = "TextWrap"

[[type_definitions.UiElement.Struct.fields]]
name = "is_input"
field_type = "Bool"

[[type_definitions.UiElement.Struct.fields]]
name = "cursor_pos"
field_type = "U32"

[[type_definitions.UiElement.Struct.fields]]
name = "scrollable_x"
field_type = "Bool"

[[type_definitions.UiElement.Struct.fields]]
name = "scrollable_y"
field_type = "Bool"

[[type_definitions.UiElement.Struct.fields]]
name = "scroll_x"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "scroll_y"
field_type = "F32"

[[type_definitions.UiElement.Struct.fields]]
name = "visible"
field_type = "Bool"

[[module_dependencies]]
module_name = "input"

[module_dependencies.version]
major = 0
minor = 1
patch = 0

[[module_dependencies]]
module_name = "graphics"

[module_dependencies.version]
major = 0
minor = 1
patch = 0
